# Generated by Django 2.2.16 on 2021-03-20 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquestionnaire',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_questionnaires', to='surveys.Questionnaire'),
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_invites', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyadvice',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_advices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyadvice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_advices', to='companies.Company'),
        ),
        migrations.AddConstraint(
            model_name='companyquestionnaire',
            constraint=models.UniqueConstraint(fields=('company', 'questionnaire'), name='company_questionnaire_unique'),
        ),
    ]
