# Generated by Django 2.2.16 on 2021-03-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210326_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairerule',
            name='company_questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='companies.CompanyQuestionnaire'),
        ),
    ]
