# Generated by Django 2.2.16 on 2021-04-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210329_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairerule',
            name='last_notified',
        ),
    ]
