PHONE_NUMBER_LENGTH = 10
COMPANY_NAME_MAX_LENGTH = 100
MAX_LENGTH = 30
WEIGHTAGE_MAX_DIGITS = 5
WEIGHTAGE_DECIMAL_PLACES = 2
EMAIL_VERIFICATION_EXPIRATION_TIME_HR = 5
DEFAULT_TOKEN_LENGTH = 20
TOKEN_MAX_LENGTH = 100
DEFAULT_RANDOM_STRING_LENGTH = 20

INTIAL_PASSWORD_LENGHT = 10
RESPONSE_MSG = 'msg'
RESPONSE_TOKEN = 'token'
PASS_UPDATE_SUCC = 'Password updated successfully.'
LOGOUT = 'Logged out'
PASS_RESET_LINK_SUCC = 'Check your email, password reset link sent successfully.'
INVALID_TOKEN = 'Invalid Token'
SUBMISSION_SUCC = 'Questionnaire submission success.'
RISK_SCORE = 'Risk score'
EMPTY_RESPONSE = 'Answer to all the questions should be provided.'
SHOULD_BELONG_TO_SAME_QUESTIONNAIRE = 'All the questions should belong to the given questionnaire.'
CHOICE_OR_USER_INPUT = 'Choice and user_input cannot be not null simultaneously.'
CHOICE_REQUIRED = 'Choice field cannot be empty for non text field question.'
USER_INPUT_REQUIRED = 'User input cannot be empty for question of type Text.'
INVALID_CHOICE = "Choice doesn't belongs to the question."
INVALID_USER_INPUT = "Invalid user input."
INVITE_SUCC_SENT = 'Invite Sent Successfully.'
INVITE_ACCEPTED = 'Invite Accepted.'
TOKEN_EXPIRED = 'Token Expired.'
COUNT = 'Count'
RULE_DISABLE = 0
RULE_ONBOARDING = 1
RULE_ONCE = 2
RULE_WEEKLY = 3
RULE_MONTHLY = 4
RULE_YEARLY = 5
RULE_DAILY = 6
RULE_MANUAL = 7
