# Generated by Django 2.2.16 on 2021-03-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_auto_20210320_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
